### ISSUE TITLE
Coding style question about `.bind()`

### ISSUE THREAD

**Issue by davej** [elierotenberg/coding-styles#1]
Feel free to ignore this, just wondering why you consider `(...params) => method.apply(this, params);` to be better than `method.bind(this);`?

To me `method.bind(this)` is much more concise and readable as it more directly describes the intention.

**Comment by elierotenberg** [comment]
`bind` is terribly slow when you just need to bind `thisArg`:
http://jsperf.com/bind-vs-scope-perf

The reason is that basically `bind` is too general and must handle a lot of edge cases (many of them related to partial `arguments` binding, which we don't need in most cases), while simply capturing `thisArg` with a closure is very simple and effective. The only downside is the confusing usage of `self = this` pattern, which can be completely avoided by using arrow functions (which are desugared to lexical `this` closuring at least by `babel`).

**Comment by elierotenberg** [comment]
An alternative is to write a helper `scope` function, which I sometimes do:

``` js
function scope(fn, thisArg) {
  return function scoped() {
     return fn.apply(thisArg, arguments);
  }:
}
```
